services:
  ffc-pay-fdmr:
    build:
      context: .
      target: production
    image: ffc-pay-fdmr
    container_name: ffc-pay-fdmr
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-fdmr-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
