# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-fdmr:
    build:
      target: development
    image: ffc-pay-fdmr-development
    container_name: ffc-pay-fdmr-development
    ports:
      - "9028:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    depends_on:
      - ffc-pay-fdmr-azurite

  ffc-pay-fdmr-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "11061:10000"

volumes:
  azurite_data:
