environment: production
environmentCode:
name: ffc-pay-fdmr
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-fdmr

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-fdmr-config-map

containerSecret:
  name: ffc-pay-fdmr-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  fdmrStorageConnectionString: myconnectionstring
  fdmrStorageShareName: fdmr
  fdmrStorageFolder: outbound
  enabled: true

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
