{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-fdmr.config-map") -}}
{{- define "ffc-pay-fdmr.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  FDMR_STORAGE_CONNECTION_STRING: {{ quote .Values.container.fdmrStorageConnectionString }}
  FDMR_STORAGE_SHARE_NAME: {{ quote .Values.container.fdmrStorageShareName }}
  FDMR_STORAGE_FOLDER_NAME: {{ quote .Values.container.fdmrStorageFolder }}
  ENABLED: {{ quote .Values.container.enabled }}
{{- end -}}
